Verify in all commit of a PR
Signed-off-by: Joel Hanson <joelhanson025@gmail.com>

diff --git a/.github/workflows/checkstyle-and-tests.yml b/.github/workflows/checkstyle-and-tests.yml
--- a/.github/workflows/checkstyle-and-tests.yml
+++ b/.github/workflows/checkstyle-and-tests.yml
@@ -7,7 +7,7 @@ on:
     types: [opened, synchronize, reopened]
 
 jobs:
-  build:
+  test:
     name: Checkstyle and Tests
     runs-on: ubuntu-latest
     steps:
@@ -28,7 +28,21 @@ jobs:
         run: mvn -X validate
       - name: Test
         run: mvn -X test
-      - name: GitLint
-        run: |
-          pip install gitlint
-          gitlint --config=gitlint/gitlint.cfg --commits master..HEAD --fail-without-commits --verbose --debug
+  verify-commits:
+    name: Verify Commits
+    runs-on: ubuntu-latest
+    steps:
+    - name: Checkout code
+      uses: actions/checkout@v2
+      with:
+        ref: ${{ github.event.pull_request.head.sha }}
+        fetch-depth: 0
+
+    - name: Verify Signed-off-by
+      run: |
+        for commit in $(git rev-list --no-merges HEAD^..HEAD); do
+          if ! git log -1 --format=%B "$commit" | grep -q "^Signed-off-by: "; then
+            echo "Commit $commit is missing Signed-off-by line."
+            exit 1
+          fi
+        done
